---
説明: healthAはAチームのコアのHPです。healthBはBチームのコアのHPです。coreA,Bはそれぞれコアとして使うブロックのIDです。
healthA: "200"
healthB: "200"
coreA: "35:14"
coreB: "35:5"
tpp:
  teamA:
    x: "132"
    "y": "4"
    z: "139"
    level: pvp
  teamB:
    x: "86"
    "y": "4"
    z: "139"
    level: pvp
...
